title: Julian Brednich
description: Technical Artist – Houdini, Python, Nuke
url: https://julianbrednich.github.io
baseurl: /Portfolio

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - README.md
  - "light creator demo.mp4"
